[tool.poetry]
name = "my-package"
version = "0.1.0"
description = "My package description"
authors = [Maha-lakshmi01 <maha.lakshmi01@infosys.com>"]
package-mode = false
[tool.poetry.dependencies]
python = ">=3.10,<3.14"
