name:  testing
on:
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
     - uses: actions/setup-python@v5
       with:
        python-version: '3.13.5'
        cache: 'pipenv'
        cache-dependency-path: |
         server/app/Pipfile.lock
         __test__/app/Pipfile.lock
     - name: Install pipenv
     - run: pipenv install
      
