name:  testing
on:
  workflow_dispatch
jobs:
  build:
     runs-on: ubuntu-latest
     steps:
      - name: Check code
      - uses: actions/checkout@v4
      - name: Python code
      - uses: actions/setup-python@v5
        with:
         python-version: '3.13.5'
         cache: 'pipenv'
      - run: pipenv install
      
        
    
       
   
      
